services:
  emailgen:
    build: .
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3002
