services:
  emailgen:
    build:
      context: .
      args:
        NEXT_PUBLIC_BETTER_AUTH_URL: https://email-gen.loopness.fr
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3002
